library(data.table)
library(lubridate)
EPC_data<-read.table("household_power_consumption.txt",header = TRUE,sep=";",na.strings = "?")
sub_data<-subset(EPC_data,Date %in% c("1/2/2007","2/2/2007"))
sub_data$Date_Time<-paste(sub_data$Date, sub_data$Time)
sub_data$Date_Time<-strptime(sub_data$Date_Time,format="%d/%m/%Y %H:%M:%S")
png("plot3.png",width=480,height = 480)
plot(x=sub_data$Date_Time,y=sub_data$Sub_metering_1,xlab="",ylab="Energy sub metering",type="l",col="black")
lines(x=sub_data$Date_Time,y=sub_data$Sub_metering_2,type = "l",col="red")
lines(x=sub_data$Date_Time,y=sub_data$Sub_metering_3,type = "l",col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = c(1,1,1))
dev.off()